title: Ulysses' trip
email: UlyssesZhan@gmail.com
description: >-
  Here we are at the awesome (awful) blog written by Ulysses Zhan!
baseurl: ""
url: "https://UlyssesZh.github.io"
twitter_username: UlyssesZhan
github_username:  UlyssesZh
header_pages: []
theme: minima
plugins:
  - jekyll-feed
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .git/
  - .idea/
